name: "NowSecure GHAS Test"

on:
 
  workflow_dispatch:
    branches: [ main ]

jobs:
    
  process:
    runs-on: ubuntu-latest
    # The above stage we introduced.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NowSecure download report
        uses: nowsecure/nowsecure-action/convert-sarif@v3
        timeout-minutes: 30
        id: getreport
        with:
          report_id: 8c7fdf66-b63f-11ed-ac54-d765fca77473
          platform_token: ${{ secrets.NSTOKEN }}
          # TODO: Replace the Group ID.
          group_id: "5d0cc76e-7309-11e7-86d0-7bac1d886ca4"
  
      - name: echo output
        run: |
         echo ${{join(steps.getreport.outputs.*, '\n')}}
        
   

    
